name: order-management

services:
    database:
        container_name: database
        image: postgres:12.8
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 3s
            retries: 20

    app:
        container_name: app
        build: .
        depends_on:
            database:
                condition: service_healthy
        ports:
            - "8080:8080"
        restart: unless-stopped
        env_file:
            - .env

volumes:
    db:
